/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ASUS
 */
public class sxJPanel extends javax.swing.JPanel {
    userservice userservice;
    
    
    /**
     * Creates new form sxJPanel
     */
    public sxJPanel() throws SQLException {
        initComponents();
        
       JTableHeader tableHeader=table.getTableHeader();
       Font headerFont=tableHeader.getFont();
       tableHeader.setFont(new Font(headerFont.getName(),Font.BOLD,20+headerFont.getSize()));
       userservice =new userservice();
       
       DefaultTableModel defaultTableModel=new DefaultTableModel();
       table.setModel(defaultTableModel);
       defaultTableModel.addColumn("TT");
       defaultTableModel.addColumn("Mã");
       defaultTableModel.addColumn("Họ và tên");
       defaultTableModel.addColumn("Ngày sinh");
       defaultTableModel.addColumn("username");
       defaultTableModel.addColumn("password");
       defaultTableModel.addColumn("Chức vụ");
       defaultTableModel.addColumn("Mức lương");
       defaultTableModel.addColumn("Giới tính");
       
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        thuattoan = new javax.swing.JLabel();
        khoa = new javax.swing.JLabel();
        thuattoanbox = new javax.swing.JComboBox<>();
        khoabox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sapxep = new javax.swing.JButton();

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("THÔNG TIN SẮP XẾP");

        thuattoan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        thuattoan.setText("THUẬT TOÁN :");

        khoa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        khoa.setText("KHÓA :");

        thuattoanbox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        thuattoanbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selection sort", "Insertion sort", "Quicksort", "Merge sort" }));

        khoabox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        khoabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã nhân viên", "Họ và tên", "Ngày sinh", "Mức lương" }));

        table.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(24);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1724, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sapxep.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        sapxep.setText("Sắp xếp");
        sapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapxepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(khoa)
                        .addGap(143, 143, 143)
                        .addComponent(khoabox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(thuattoan)
                        .addGap(61, 61, 61)
                        .addComponent(thuattoanbox, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sapxep)
                .addGap(473, 473, 473))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thuattoan)
                    .addComponent(thuattoanbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khoa)
                    .addComponent(khoabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sapxep))
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new menu1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapxepActionPerformed
        // TODO add your handling code here:
    DefaultTableModel defaultTableModel=new DefaultTableModel();
       table.setModel(defaultTableModel);
       defaultTableModel.addColumn("TT");
       defaultTableModel.addColumn("Mã");
       defaultTableModel.addColumn("Họ và tên");
       defaultTableModel.addColumn("Ngày sinh");
       defaultTableModel.addColumn("username");
       defaultTableModel.addColumn("password");
       defaultTableModel.addColumn("Chức vụ");
       defaultTableModel.addColumn("Mức lương");
       defaultTableModel.addColumn("Giới tính");
        if((String)thuattoanbox.getSelectedItem()=="Selection sort"){
       ArrayList<user> users = null;
            try {
                users = userservice.selectionsort((String)khoabox.getSelectedItem());
            } catch (SQLException ex) {
                Logger.getLogger(sxJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
       
       
       for(user user:users){
           defaultTableModel.addRow(new Object[]{user.getTt(),user.getId(),user.getName(),user.getNs(),user.getUsername(),user.getPassword(),user.getChucvu(),user.getMucluong(),user.getGt()});
       }
    }
        else if((String)thuattoanbox.getSelectedItem()=="Insertion sort"){
            ArrayList<user> users=null;
            try {
                users=userservice.insertionsort((String)khoabox.getSelectedItem());
            } catch (SQLException ex) {
                Logger.getLogger(sxJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(user user:users){
           defaultTableModel.addRow(new Object[]{user.getTt(),user.getId(),user.getName(),user.getNs(),user.getUsername(),user.getPassword(),user.getChucvu(),user.getMucluong(),user.getGt()});
       }
        }
        else if((String)thuattoanbox.getSelectedItem()=="Quicksort"){
            ArrayList<user> users=null;
        try {
            users=userservice.quicksort1((String)khoabox.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(sxJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         for(user user:users){
           defaultTableModel.addRow(new Object[]{user.getTt(),user.getId(),user.getName(),user.getNs(),user.getUsername(),user.getPassword(),user.getChucvu(),user.getMucluong(),user.getGt()});
       }
        }
        else if((String)thuattoanbox.getSelectedItem()=="Merge sort"){
            ArrayList<user> users=null;
        try {
            users=userservice.mergesort1((String)khoabox.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(sxJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         for(user user:users){
           defaultTableModel.addRow(new Object[]{user.getTt(),user.getId(),user.getName(),user.getNs(),user.getUsername(),user.getPassword(),user.getChucvu(),user.getMucluong(),user.getGt()});
       }
        }
    }//GEN-LAST:event_sapxepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel khoa;
    private javax.swing.JComboBox<String> khoabox;
    private javax.swing.JButton sapxep;
    private javax.swing.JTable table;
    private javax.swing.JLabel thuattoan;
    private javax.swing.JComboBox<String> thuattoanbox;
    // End of variables declaration//GEN-END:variables
}
