/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class themJPanel extends javax.swing.JPanel {
    userservice userservice;
    user user;
    /**
     * Creates new form themJPanel
     */
    public themJPanel() {
        initComponents(); 
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        quaylaiButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        malabel = new javax.swing.JLabel();
        tenlabel = new javax.swing.JLabel();
        tentext = new javax.swing.JTextField();
        nslabel = new javax.swing.JLabel();
        nstext = new javax.swing.JTextField();
        tklabel = new javax.swing.JLabel();
        tktext = new javax.swing.JTextField();
        mklabel = new javax.swing.JLabel();
        mktext = new javax.swing.JPasswordField();
        chucvulabel = new javax.swing.JLabel();
        chucvutext = new javax.swing.JTextField();
        mucluonglabel = new javax.swing.JLabel();
        mucluongtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nambox = new javax.swing.JCheckBox();
        nubox = new javax.swing.JCheckBox();
        nopButton = new javax.swing.JButton();
        matext = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        quaylaiButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        quaylaiButton.setText("Quay lại");
        quaylaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylaiButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        malabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        malabel.setText("Mã Nhân Viên :");

        tenlabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tenlabel.setText("Họ và tên :");

        tentext.setFont(new java.awt.Font("Arial", 0, 24));

        nslabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        nslabel.setText("Ngày sinh :");

        nstext.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        tklabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tklabel.setText("Tên tài khoản :");

        tktext.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        mklabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        mklabel.setText("Mật khẩu :");

        mktext.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        chucvulabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        chucvulabel.setText("Chức vụ :");

        chucvutext.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        mucluonglabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        mucluonglabel.setText("Mức lương :");

        mucluongtext.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Giới tính :");

        nambox.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        nambox.setText("Nam");

        nubox.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        nubox.setText("Nữ");
        nubox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuboxActionPerformed(evt);
            }
        });

        nopButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        nopButton.setText("Thêm mới");
        nopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopButtonActionPerformed(evt);
            }
        });

        matext.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        matext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matextMouseClicked(evt);
            }
        });
        matext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quaylaiButton)
                .addGap(337, 337, 337)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nopButton)
                .addGap(494, 494, 494))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(malabel)
                        .addGap(18, 18, 18)
                        .addComponent(matext, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tklabel)
                            .addComponent(tenlabel)
                            .addComponent(mklabel)
                            .addComponent(mucluonglabel))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mktext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                                    .addComponent(tktext, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tentext, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(542, 542, 542))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mucluongtext, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                                .addGap(546, 546, 546))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(82, 82, 82)
                        .addComponent(nambox)
                        .addGap(175, 175, 175)
                        .addComponent(nubox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chucvulabel)
                                .addGap(17, 17, 17))
                            .addComponent(nslabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nstext, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                            .addComponent(chucvutext))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(quaylaiButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenlabel)
                    .addComponent(tentext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tklabel)
                            .addComponent(tktext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mklabel)
                            .addComponent(mktext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mucluongtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mucluonglabel))
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chucvulabel)
                        .addComponent(chucvutext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nslabel)
                    .addComponent(nstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nambox)
                    .addComponent(nubox))
                .addGap(75, 75, 75)
                .addComponent(nopButton)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuboxActionPerformed

    private void nopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopButtonActionPerformed
        // TODO add your handling code here:
        user.setId(matext.getText());
        user.setName(tentext.getText());
        user.setNs(nstext.getText());
        user.setUsername(tktext.getText());
        user.setPassword(String.valueOf(mktext.getPassword()));
        user.setChucvu(chucvutext.getText());
        user.setMucluong(mucluongtext.getText());
        String gt="";
        if(nambox.isSelected()){
            gt+="Nam";
        }
        if(nubox.isSelected()){
            gt+="Nữ";
        }
        user.setGt(gt);
        userservice.adduser(user);
//        JOptionPane showMessageDialog = JOptionPane.showMessageDialog(add.this,"Bạn đã thêm thành công!!!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        
        new menu1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nopButtonActionPerformed

    private void quaylaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylaiButtonActionPerformed
        // TODO add your handling code here:
        new menu1().setVisible(true);
//    this.disable();
    }//GEN-LAST:event_quaylaiButtonActionPerformed

    private void matextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matextActionPerformed

    private void matextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matextMouseClicked
        // TODO add your handling code here:
         matext.setEditable(true);
    }//GEN-LAST:event_matextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chucvulabel;
    private javax.swing.JTextField chucvutext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel malabel;
    private javax.swing.JTextField matext;
    private javax.swing.JLabel mklabel;
    private javax.swing.JPasswordField mktext;
    private javax.swing.JLabel mucluonglabel;
    private javax.swing.JTextField mucluongtext;
    private javax.swing.JCheckBox nambox;
    private javax.swing.JButton nopButton;
    private javax.swing.JLabel nslabel;
    private javax.swing.JTextField nstext;
    private javax.swing.JCheckBox nubox;
    private javax.swing.JButton quaylaiButton;
    private javax.swing.JLabel tenlabel;
    private javax.swing.JTextField tentext;
    private javax.swing.JLabel tklabel;
    private javax.swing.JTextField tktext;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
         //To change body of generated methods, choose Tools | Templates.
    }

    
}
