/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ASUS
 */
public class timkiemJPanel extends javax.swing.JPanel {
    userservice userservice;
    /**
     * Creates new form timkiemJPanel
     */
    public timkiemJPanel() {
        initComponents();
//        JTableHeader tableHeader=table.getTableHeader();
//       Font headerFont=tableHeader.getFont();
//       tableHeader.setFont(new Font(headerFont.getName(),Font.BOLD,20+headerFont.getSize()));       
    userservice =new userservice();
       
//        DefaultTableModel defaultTableModel=new DefaultTableModel();
//       table.setModel(defaultTableModel);
//       defaultTableModel.addColumn("TT");
//       defaultTableModel.addColumn("Mã");
//       defaultTableModel.addColumn("Họ và tên");
//       defaultTableModel.addColumn("Ngày sinh");
//       defaultTableModel.addColumn("username");
//       defaultTableModel.addColumn("password");
//       defaultTableModel.addColumn("Chức vụ");
//       defaultTableModel.addColumn("Mức lương");
//       defaultTableModel.addColumn("Giới tính");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        khoa = new javax.swing.JComboBox<>();
        timkiem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        giatrikhoa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        thuattoan = new javax.swing.JComboBox<>();

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Quay lại");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("THÔNG TIN TÌM KIẾM");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("THUẬT TOÁN :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("KHÓA :");

        table.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(24);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1705, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );

        khoa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        khoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chức vụ", "Mã nhân viên", "Họ và tên", "Ngày sinh", "Mức lương" }));

        timkiem.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        timkiem.setText("Tìm kiếm");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("GIÁ TRỊ KHÓA :");

        giatrikhoa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        giatrikhoa.setText("Nhấn vào giá trị để nhập");
        giatrikhoa.setToolTipText("");
        giatrikhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giatrikhoaActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setText("Giá trị");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        thuattoan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        thuattoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tuần tự", "Nhị phân" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(694, 694, 694)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(khoa, 0, 413, Short.MAX_VALUE)
                            .addComponent(thuattoan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jButton2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timkiem)
                            .addComponent(giatrikhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(thuattoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timkiem)
                                    .addComponent(jButton2))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(giatrikhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("null")
    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
        // TODO add your handling code here:
       
       DefaultTableModel defaultTableModel=new DefaultTableModel();
       table.setModel(defaultTableModel);
       defaultTableModel.addColumn("TT");
       defaultTableModel.addColumn("Mã");
       defaultTableModel.addColumn("Họ và tên");
       defaultTableModel.addColumn("Ngày sinh");
       defaultTableModel.addColumn("username");
       defaultTableModel.addColumn("password");
       defaultTableModel.addColumn("Chức vụ");
       defaultTableModel.addColumn("Mức lương");
       defaultTableModel.addColumn("Giới tính");
       
       
       if((String)thuattoan.getSelectedItem()=="Tuần tự"){
           ArrayList<user> users = null;
           try {
                 users=userservice.tuantu((String)khoa.getSelectedItem(),giatrikhoa.getText());
            } catch (SQLException ex) {
                Logger.getLogger(timkiemJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
             for(user user:users){
           defaultTableModel.addRow(new Object[]{user.getTt(),user.getId(),user.getName(),user.getNs(),user.getUsername(),user.getPassword(),user.getChucvu(),user.getMucluong(),user.getGt()});
       }
       }
      if((String)thuattoan.getSelectedItem()=="Nhị phân"){
         String kind = (String)khoa.getSelectedItem();
         String a = giatrikhoa.getText();
          ArrayList<user> users=null ;
            try {
                users = userservice.timkiemnhiphan(kind,a);
            } catch (SQLException ex) {
                Logger.getLogger(timkiemJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(timkiemJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
             for(user user:users){
           defaultTableModel.addRow(new Object[]{user.getTt(),user.getId(),user.getName(),user.getNs(),user.getUsername(),user.getPassword(),user.getChucvu(),user.getMucluong(),user.getGt()});
       }
       }
        
    }//GEN-LAST:event_timkiemActionPerformed

    private void giatrikhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giatrikhoaActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_giatrikhoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String inputData = JOptionPane.showInputDialog("Nhập giá trị khóa:");

        giatrikhoa.setText(inputData);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField giatrikhoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> khoa;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> thuattoan;
    private javax.swing.JButton timkiem;
    // End of variables declaration//GEN-END:variables
}
